name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: Download a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
        name: build
        # Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE
        path: build
